# Generated by Django 6.0 on 2025-12-25 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_completed',
        ),
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.PositiveIntegerField(default=16, help_text="User's age in years"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='Hey! Just another fellow member in the club!', help_text='Short bio (max 500 characters)', max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='programming_experience',
            field=models.TextField(help_text='Description of programming background and experience'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='school',
            field=models.CharField(help_text='Current school/institution', max_length=200),
        ),
    ]
